version: "3.9"
services:
  Bot:
    image: avespoir:latest
    build: .
    stop_signal: SIGTERM
    container_name: Avespoir
    volumes:
      - ./Configs:/Avespoir/Configs
      - ./Log:/Avespoir/Log
